### ISSUE TITLE
Add new header poster tool

### ISSUE THREAD

**Issue by ukantjadia** [dhyeythumar/awesome-readme-tools#8]
Hey! I found this very useful,
It can be helpful to others also.
[https://leviarista.github.io/github-profile-header-generator/](https://leviarista.github.io/github-profile-header-generator/)

**Comment by dhyeythumar** [comment]
Hi
Can you create a PR and add the GitHub link - https://github.com/leviarista/github-profile-header-generator
Add this tool under the Miscellaneous section.
